# Generated by Django 6.0 on 2025-12-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('game_type', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('document', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
