# Generated by Django 6.0 on 2025-12-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='player_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='player_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='team_id',
            field=models.CharField(blank=True, default='7680305', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='team_name',
            field=models.CharField(blank=True, default='Lucky Cricket Aca', max_length=300),
        ),
    ]
