# Generated by Django 6.0 on 2025-12-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_player_id_student_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_matches',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='total_runs',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='total_wickets',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
