# Generated by Django 6.0 on 2025-12-11 03:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_average_student_economy_student_fours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount', models.FloatField(default=200)),
                ('paid_on', models.DateField(default=datetime.date.today)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.student')),
            ],
            options={
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
