# Generated by Django 6.0 on 2025-12-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='amount',
            field=models.FloatField(blank=True),
        ),
    ]
